# Goal-setting

Our purpose today is to set some goals for yourself that you can act on this summer

## What would you like to revisit from your values and workflow last week? 

::: {.callout-tip appearance="minimal" icon="false"}

<!---p.1--->

*What drives you? Who are your allies, colleagues, and mentors that give you energy and support?*

 
better understand the linkage between values and workflows
Email and listing (not forgetting) and prioritizing tasks
Steffi, Pete, Bernadette, Phil - my cheer leaders and editors :)
 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 
:::

## What goals are emerging for your workflow?

::: {.callout-tip appearance="minimal" icon="false"}

<!---p.2--->

*Dream big. Why are you committed to these goals?*
Organization and effiency
Disorganization and low effiency are a source of stress
Getting my shit together will allow me to focus on the parts of my job that bring me joy
  

 

  

 

 

 
 

 

  

  

 

  

  

 

:::


## What pieces do you have control over in the short and long term? 

::: {.callout-tip appearance="minimal" icon="false"}

<!---p.2--->

*What are the possibilities? And what are the barriers? What questions do you need answered, what conversations do you need to have?*

CRC -> need excellent, resilient and robust workflows
Barriers include motivation, time and skills, the desire to have it NOW
What is my biggest stumbling block can and do I want to take on more?

 

  

 

 

 
 

 

  

  

 

  

  

 


:::

## What actions can you take this summer in service of these bigger goals?

::: {.callout-tip appearance="minimal" icon="false"}


<!---p.3--->

*What would you like to experiment with? Where is a place you could try something new? For example - if I feel behind every morning, what would it look like to not set meetings before 10am?*

Workflowy
blocking out times for different activities
Clean inbox :)
  

 

  

 

  

  

 

  
  
 

 

 
 

 

  

  

 

  

  

 

 

  

  

 

  

 

 

 
 

 

  

  

 

  

  

 


:::

## What would success look like? 

::: {.callout-tip appearance="minimal" icon="false"}

<!---p.3--->

*What feedback would you need from yourself to know if your actions/ experiment is working or needs to be iterated? How can you give yourself grace?*

Feeling less stressed
Feeling like I got my shit together - not bouncing from task to task because of deadlines, feeling confident
recognize my anxiety over this and take a mindful moment as needed
  

 

  

 

 

 
 

 

  

  

 

  

  

 

:::



## What do you need to make this possible? 

::: {.callout-tip appearance="minimal" icon="false"}

<!---p.4--->

*What support or accountability could help you? For example, journaling or sharing progress with a colleague for a set period of time*

Steffi
sharing with a collegue
Personal coaching
 

  

 

 

 
 

 

  

  

 

  

  

 

:::


## What’s something you’re excited about that you could share with others? 

::: {.callout-tip appearance="minimal" icon="false"}

<!---p.5--->

not sure. hesitant to get started - fear of failing
Decided to get a paid workflowy account to help manage my tasks and keep track of important information
  

 

  

 

  

  

 

  
  
 

 

 
 

 

  

  

 

  

  

 

 

  

  

 

  

 

 

 
 

 

  

  

 

  

  

 

:::
