# Reflect

Our purpose today is to notice – what works, what doesn’t work? We’ll think about your workflows and how you collaborate.

## What are things you know about yourself and how you work? 
::: {.callout-note appearance="minimal" icon="false"}
<!---p.1--->
*What are the conditions when you do your best work? This could be things like I write best in the mornings, I am comfortable speaking up in new spaces.*
*Best Working conditions*
- Feeling good e.g., not tired
- Nice work space
- Working on a project that I like
- Working with others who are actually helping/doing their part

*Poor Working conditions*
- Responding to email as they come in
- Working on too many things at once
- Feeling unmotivated
- Not sure how to move forward

 

I can get easily distracted
I have a hard time priortizing certain work items, especially those that have no deadline and/or do not involve others


 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 
:::


## What software do you use, and for what purposes?  

::: {.callout-note appearance="minimal" icon="false"}

<!---p.2--->

*Think across your different workflows. Where do you do your writing? How do you manage citations or versions? Do you take screenshots? If you analyze data or images, what do you use?*

R and R studio for data anlsysis
Zotero for managing references
Dropbox for syncing across home and work computers, also for working collaborativly on projects (share data, documents etc)
OSF working with a grad student to manage and archive data
MS office and open office for writing documents
Converting many of my university assignments to quarto documents
Google sheets and docs for working with others
One drive for work/department related files
ImageJ - image analysis
Google drive - sharing documents
Quarto for helping students with R related questions

  

 

  

 

 

 
 

 

  

  

 

  

  

 
:::

## What kinds of files do you work with? 

::: {.callout-note appearance="minimal" icon="false"}

<!---p.2--->

*How do you organize them? Do you download and save in folders? How do you find them?*

- docs, spreadsheets, csv, images, propietary file types (e.g., data exported from intruments), .shp
- organized by project and/or collaborator and/or site location - trouble with overlap
- download and save, backed up via drop box 
- find them by memory or searching within folders

 

  

 

 

 
 

 

  

  

 

  

  

 

:::

## What does your workflow look like? 

::: {.callout-note appearance="minimal" icon="false"}

<!---p.3--->

*You can do this think of a specific project or piece of your workflow, or multiple projects. What does an example day or week look like? How do software and files connect together? You can draw this*

Work flow is often chaotic at best, try to set up in a logical mannor at first but don't know what to do with unknowns or unexpected changes to a project. I am reluctant to make changes later on

Every project/task is a different work flow

Projects are split into into subprojects. Each subproject will have its folder, where data, scripts and results are put. Usully have a separate writing folder

No two days seem to be the same unexpected things always seem to come up and I am not great at organizing and priortizing.
  

 

  

 

  

  

 

  
  
 

 

 
 

 

  

  

 

  

  

 

 

  

  

 

  

 

 

 
 

 

  

  

 

  

  

 
:::


## How do you track tasks for your workflow? 

::: {.callout-note appearance="minimal" icon="false"}

<!---p.4--->

*Do you write notes to yourself or document your process? Do you use sticky notes, apps, a document, a calendar? Do you take screenshots? How do you find things weekly or come back to something after a month, a year?*

  White board and sticky notes and my google calendar are my main ways or tracking things and not forgetting about them
  Will leave comments in R scripts to note where I left off and what needs to be done next
  Often search my email archive for inforamtion 

 

  

 

 

 
 

 

  

  

 

  

  

 


:::

## How do you collaborate with colleagues? 

::: {.callout-note appearance="minimal" icon="false"}

<!---p.4--->

*Who is included in your workflow? How do you share files and communicate? If you think "I work alone", consider who you talk to, how do you give and receive feedback?*

Drop box
email
OSF
google drive
github

Admin
Students
Faculty
Academic/government research partners
Industry groups

 

  

 

 

 
 

 

  

  

 

  

  

 


:::

## What feels good about your workflow? 

::: {.callout-note appearance="minimal" icon="false"}

<!---p.5--->

*There are good things about your workflow. What feels good to you?*

For some aspects of my job it's a well organized and functional workflow - makes me feel competent
When it works as anticipated and can handle unknowns and the unexpected, and the curosity side tracks
Empty inbox feels awesome!
Everything is backed up

 

  

 

 

 
 

 

  

  

 

  

  

 

:::

## What feels clunky about your workflow? 

::: {.callout-note appearance="minimal" icon="false"}


<!---p.5--->

*Are there places you suspect take longer than they should or could improve in other ways? Are there things you find yourself repeating a lot (copy-pasting, clicking?)*

In many cases i don't have one or its not really working for me.
Have a hard time findingout how I did it last time
Responding to prospective grad students when I am not activly requiting. I type out the same message in my reply - get several a week 
keeping track of emails that need action or follow up

  

 

  

 

 

 
 

 

  

  

 

  

  

 

 

  

  

 
:::


## What is top-of-mind for you?

::: {.callout-note appearance="minimal" icon="false"}

<!---p.6--->

*What might be a focus for the next few weeks?*

How to organize files in a meaningful and functional way  
How do I handle so many very different tasks in a unifying way and keep track of it all
How can I better manage my inbox

 

  

 

  

  

 

  
  
 

 

 
 

 

  

  

 

  

  

 

 

  

  

 

  

 

 

 
 

 

  

  

 

  

  

 

:::
