# Reimagine

Our purpose today is to spot things that could help your workflow. The ideas is to reuse what works (for you and others), and ease off what doesn’t work


## What resonates for you from last week?

::: {.callout-caution appearance="minimal" icon="false"}

<!---p.1--->

*Revisit what was top-of-mind from last week. What else has emerged? What patterns, if any, are coming up for you?*

Not the only one who feels a bit disorganized. Very neat to see what people are doing and interesting to see the issue people run into.
The idea of using a ggogle doc to document meetings
 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 
:::

## Where within your workflow seems like a good place to start iterating?

::: {.callout-caution appearance="minimal" icon="false"}

<!---p.2--->

*What stands out about that place? Why are you motivated to focus on this part of your workflow?*

Email -> responding to everyone and keeping track of incompleted or ongoing threads. I forget about things and people - it does not make me feel great. It is also the part of my job that I find little joy in. Makes me feel like I have a cluttered brain, hard to focus and prioritize. I feel like this is lowing hanging fruit with possibe high dividends 

 

  

 

 

 
 

 

  

  

 

  

  

 

:::


## Think of a good workflow you’ve seen. What felt good about it? 

::: {.callout-caution appearance="minimal" icon="false"}

<!---p.2--->

*For example, what was it about how it was organized, how different people contributed, how it was communicated? Remember meetings are part of workflows too*
So organized, slick, professional, demonstrated competence, exuded confidence. Made the task faster and easier to come back to

  

 

  

 

 

 
 

 

  

  

 

  

  

 


:::

## What have you seen or heard about that has you curious? 

::: {.callout-caution appearance="minimal" icon="false"}

<!---p.2--->

*What are things you’d like to learn or reuse from what you’ve seen? Think from colleagues, talks, and examples online*

What are common organizational structure and tags used in email inboxes
The use of google docs to track important items
Learn discipline to use/develop work flows
  

 

  

 

  

  

 

  
  
 

 

 
 

 

  

  

 

  

  

 

 

  

  

 

  

 

 

 
 

 

  

  

 

  

  

 


:::

## What are some of your values?

::: {.callout-caution appearance="minimal" icon="false"}

<!---p.3--->

*Think about something you enjoy doing. What qualities about yourself do you see coming through? What is important to you personally and professionally? How do you want to make people feel?*

Outdoor recreation -> competence, strength, confidence

I want to feel and be seen as succesful 
I want to feel and be seen as dependable
I want to find joy in my work
  

 

  

 

 

 
 

 

  

  

 

  

  

 

:::

## How do your values show up in your workflow, and how you interact with colleagues?

::: {.callout-caution appearance="minimal" icon="false"}


<!---p.3--->

*How do you show up in your daily life at work? For example, being on time, being organized, interacting with people.*

I am genaerally on time and prepared for meetings. try hard to contribute and keep people on the agenda
A great work flow brings me joy 
Sharing solution with a good work makes me feel confidence and competent

 

 
 

 

  

  

 

  

  

 

 

  

  

 
:::


## What would it look like to connect your values more with your workflow?

::: {.callout-caution appearance="minimal" icon="false"}

<!---p.4--->

*Think about that place that seems like a good place to focus. What if you brought what you have seen and want to learn to that place, along with your values? You can draw this*

glorious!
Stress levels decreasing

 

  

 

  

  

 

  
  
 

 

 
 

 

  

  

 

  

  

 

 

  

  

 

  

 

 

 
 

 

  

  

 

  

  

 

:::
